### ISSUE TITLE
Reset your API key

### ISSUE THREAD

**Issue by sequoiia** [Kawahal/league-win#1]
Hey, looks like you have committed your API key in [src/main/java/Main.java](https://github.com/Kawahal/league-win/blob/master/src/main/java/Main.java)

**Comment by Kawahal** [comment]
Thanks! Didn't notice, I can't believe i did shuch a bad mistake. I was still trying the api and I had tons of stuff in my head, so I forgot.

**Comment by sequoiia** [comment]
No problem :+1:
